### PR TITLE
Update README.md

### LINKED ISSUE #2: Update FAQ
Out of date documentation. Works fine on Windows 10 with Linux subsystem installed. Example: https://twitter.com/coolstarorg/status/797200322259132417

:)

### PR DESCRIPTION
**Pull request by hmemcpy**
Adds Windows compatibility note. Fixes #2.

### CODE REVIEW

**Comment by benrady** [comment]
I honestly cannot tell if you're trolling me right now.

**Comment by hmemcpy** [comment]
Absolutely not. Running native bash on Windows is totally a thing now, so your script "just works™"

**Comment by leonardosnt** [comment]
@benrady It works

**Comment by benrady** [comment]
I can't accept any pull requests that compromise the artistic integrity of this project (as defined by the README)

**Pull request closed without merging**
