### PR TITLE
Use printf to print equal signs multiple times

### PR DESCRIPTION
**Pull request by nir0s**

### CODE REVIEW

**Comment by benrady** [comment]
On which platforms is printf installed by default?

**Comment by nir0s** [comment]
Um.. printf is a part of bash since 4.1.7 I believe.

**Comment by nir0s** [comment]
And btw, since performance is very important here, printf is faster :)

**Comment by benrady** [comment]
Looks like it's also part of the coreutils package in Homebrew. 

```
brady$ which printf
/usr/local/opt/coreutils/libexec/gnubin/printf

**Comment by Artoria2e5** [comment]
> Looks like it's also part of the coreutils package in Homebrew.

Seriously, stop using `which`. It only knows about commands in your PATH and ignores those builtin ones.

```
$ type printf
printf is a shell builtin

$ type cat
cat is hashed (/usr/bin/cat)

$ type if
if is a shell keyword

```

**Comment by j8r** [comment]
Personally I'm against this PR because this will remove the POSIX compliance of this little script. However we can replace the `echo -en` by `printf`.
Finally we should replace `#!/usr/bin/env bash` by `#!/usr/bin/env sh`

**Pull request closed without merging**
