### PR TITLE
Use -p flag in nc

### PR DESCRIPTION
**Pull request by nir0s**

### CODE REVIEW

**Comment by nir0s** [comment]
Am I wrong to assume that `-p` will always work?

**Comment by hmemcpy** [comment]
Yup, I needed the `-p` flag to make this work inside a docker container...

**Comment by benrady** [comment]
For BSD netcat, the -p option is incompatible with the -l option. From the man page:

```
     -p source_port
             Specifies the source port nc should use, subject to privilege
             restrictions and availability.  It is an error to use this option
             in conjunction with the -l option.
```

What netcat are you using?

**Comment by nir0s** [comment]
0.7.1 on rolling arch

**Pull request closed without merging**
